package POJO;
// Generated 01-mar-2016 8:17:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriaprofesional generated by hbm2java
 */
public class Categoriaprofesional  implements java.io.Serializable {


     private Integer codCategoria;
     private String descripcionCategoria;
     private Set contratos = new HashSet(0);
     private Set nominas = new HashSet(0);

    public Categoriaprofesional() {
    }

	
    public Categoriaprofesional(String descripcionCategoria) {
        this.descripcionCategoria = descripcionCategoria;
    }
    public Categoriaprofesional(String descripcionCategoria, Set contratos, Set nominas) {
       this.descripcionCategoria = descripcionCategoria;
       this.contratos = contratos;
       this.nominas = nominas;
    }
   
    public Integer getCodCategoria() {
        return this.codCategoria;
    }
    
    public void setCodCategoria(Integer codCategoria) {
        this.codCategoria = codCategoria;
    }
    public String getDescripcionCategoria() {
        return this.descripcionCategoria;
    }
    
    public void setDescripcionCategoria(String descripcionCategoria) {
        this.descripcionCategoria = descripcionCategoria;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }




}


