package POJO;
// Generated 02-mar-2016 22:47:44 by Hibernate Tools 4.3.1



/**
 * Coordinadordpto generated by hbm2java
 */
public class Coordinadordpto  implements java.io.Serializable {


     private Integer codigo;
     private Departamento departamento;
     private Empleado empleado;

    public Coordinadordpto() {
    }

    public Coordinadordpto(Departamento departamento, Empleado empleado) {
       this.departamento = departamento;
       this.empleado = empleado;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


