package POJO;
// Generated 28-feb-2016 22:06:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Depatamento generated by hbm2java
 */
public class Depatamento  implements java.io.Serializable {


     private Integer codDpto;
     private String nombreDpto;
     private Set coordinadordptos = new HashSet(0);
     private Set empleados = new HashSet(0);

    public Depatamento() {
    }

	
    public Depatamento(String nombreDpto) {
        this.nombreDpto = nombreDpto;
    }
    public Depatamento(String nombreDpto, Set coordinadordptos, Set empleados) {
       this.nombreDpto = nombreDpto;
       this.coordinadordptos = coordinadordptos;
       this.empleados = empleados;
    }
   
    public Integer getCodDpto() {
        return this.codDpto;
    }
    
    public void setCodDpto(Integer codDpto) {
        this.codDpto = codDpto;
    }
    public String getNombreDpto() {
        return this.nombreDpto;
    }
    
    public void setNombreDpto(String nombreDpto) {
        this.nombreDpto = nombreDpto;
    }
    public Set getCoordinadordptos() {
        return this.coordinadordptos;
    }
    
    public void setCoordinadordptos(Set coordinadordptos) {
        this.coordinadordptos = coordinadordptos;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


